### ISSUE TITLE
Respec

### ISSUE THREAD

**Issue by BanditJojo** [Boyos999/tes3mp-xp#1] opened 2022-02-20 19:31 UTC
Initial respec system worked fine, I was able to allocate points where I wanted, however I only allocated trait points for no reason other than I wanted to. Half way through my respec I decided to start over again. My max level went from 14 to 9, I kept all my trait points despite the journal telling me I never spent any. I was able to respend my trait points, most of my traits were very high and with 90+ points I could have had everything at 100 by level 3. I never spent any points on skills during this time b/c once I saw how I borked the script I rerolled a backup character.

**Comment by Boyos999** [comment] 2022-02-20 21:05
This should now be fixed by this commit https://github.com/Boyos999/tes3mp-xp/commit/51f2bbb16ff01911b034ec9d03a0626e8ddad24f

Losing max levels: This was caused by the respec code not accounting for unspent level ups.

Respecs after 1st respec not properly respecing skills/attrs: This was caused by some programmer stuff about how lua handles table references that I don't fully understand but should be fixed.

**Closed as completed by Boyos999** 2022-02-20 21:05 UTC
